config/routes.rb
Rails.application.routes.draw do
  get 'api/index'

  get 'home/index'

  get '/:locale', locale: /en|ja|vi/, to: 'home#index'
  root to: 'home#index'

  scope '(:locale)', locale: /en|ja|vi/ do
    devise_for :users, skip: [:registrations, :unlocks], controllers: {
      # registrations: 'users/registrations',
      # unlocks: 'users/unlocks',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
    }

    as :user do
      get    'sign_up', to: 'users/registrations#new',
        as: :new_user_registration
      get    'users/cancel',  to: 'users/registrations#cancel',
        as: :cancel_user_registration
      post   'users',         to: 'users/registrations#create',
        as: :user_registration
      delete 'users',         to: 'users/registrations#destroy'

      get    'settings/password', to: 'users/settings/passwords#edit',
        as: :edit_user_settings_password
      put    'settings/password', to: 'users/settings/passwords#update',
        as: :user_settings_password
      patch  'settings/password', to: 'users/settings/passwords#update'

      get    'settings/account', to: 'users/settings/accounts#edit',
        as: :edit_user_settings_account
      put    'settings/account', to: 'users/settings/accounts#update',
        as: :user_settings_account
      patch  'settings/account', to: 'users/settings/accounts#update'
    end

    namespace :users do
      post '/:user_id', to: 'followings#create', as: :followings
      delete '/:user_id', to: 'followings#destroy'
    end

    scope module: :profiles do
      get ':user_id', action: :show, as: :profile
      get ':user_id/mentions', action: :mentions, as: :profile_mentions
      get ':user_id/followers', action: :followers, as: :profile_followers
      get ':user_id/following', action: :following, as: :profile_following
      get ':user_id/likes', action: :likes, as: :profile_likes
    end

    scope module: :feeds do
      resources :tweets, only: [:show, :update, :create, :destroy] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    scope module: :replies do
      resources :replies, only: [] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    resources :tweets, only: [] do
      resources :replies, shallow: true, controller: "tweets/replies" do
        resources :replies, only: [:create, :new, :index], controller: "tweets/replies"
      end

      resources :hashtags, shallow: true, only: :show, controller: "tweets/hashtags"
    end

    namespace :search do
      get 'users'
      get 'hashtags'
      get 'tweets'
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, :find_user

  decorates_assigned :user, :user_following, :user_followers, :feeds

  def show
    @feeds = Feed.tweets_of(user)
  end

  def followers
    @user_followers = UserDecorator.decorate_collection(@user.followers)
  end

  def following
    @user_following = UserDecorator.decorate_collection(@user.followings)
  end

  def likes
    @feeds = Feed.where(id: @user.likeds)
  end

  def mentions
    @mentioned_tweets = @user.mentioned_tweets
    @feeds = Feed
      .includes(tweet: [:user])
      .where(feedable: @mentioned_tweets)
  end

  def current_user_profile?
    @user == current_user
  end

  helper_method :current_user_profile?

private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_path?(user)
    current_page?(profile_path(user))
  end

  def profile_following_path?(user)
    current_page?(profile_following_path(user))
  end

  def profile_followers_path?(user)
    current_page?(profile_followers_path(user))
  end

  def profile_likes_path?(user)
    current_page?(profile_likes_path(user))
  end
end

app/views/profiles/_pheader.html.slim
div.profile-header-container
  div.profile-cover
    = image_container(user.cover.url, "3_1")

    div.profile-avatar
      div.container
        div.avatar-original [data-toggle="tooltip" data-placement="right"
          title="#{user.profilename}"]

          = image_container(user.avatar.url, "1_1", true)

  div.profile-nav
    div.container
      div.row
        div.col-3

        div.col-9
          div.profile-nav-buttons-group
            ul.nav
              li.nav-item
                = link_to profile_path(user.username),
                  class: class_names("nav-link", active: profile_path?(user)) do
                  span.profile-stat-label
                    = t(:tweets, scope: "views.users.shared")
                  span.profile-stat-value
                    | 6
              li.nav-item
                = link_to profile_following_path(user.username),
                  class: class_names("nav-link", active: profile_following_path?(user)) do
                  span.profile-stat-label
                    = t(:following, scope: "views.users.shared")
                  span.profile-stat-value
                    = user.followings.count
              li.nav-item
                = link_to profile_followers_path(user.username),
                  class: class_names("nav-link", active: profile_followers_path?(user)) do
                  span.profile-stat-label
                    = t(:followers, scope: "views.users.shared")
                  span.profile-stat-value
                    = user.followers.count
              / li.nav-item
              /   = link_to profile_likes_path(user.username),
              /     class: class_names("nav-link", active: profile_likes_path?(user)) do
              /     span.profile-stat-label
              /       = t(:likes, scope: "views.users.shared")
              /     span.profile-stat-value
              /       | 169

            - unless current_user_profile?
              = user.follow_buttons

app/views/profiles/_pleft.html.slim
div.profile-left-panel
  = user.names_multilines(true)

  - if user.introduction
    p.profile-introduction == user.introduction

  - if user.country
    div.profile-extra-content
      i class="fas fa-map-marker-alt fa-fw"
      = user.country

  div.profile-extra-content
    i class="fas fa-calendar-alt fa-fw"
    = user.created_at

  - if user.birthday
  div.profile-extra-content
    i class="fas fa-birthday-cake fa-fw"
    = user.birthday

app/views/profiles/_tnav.html.slim
ul.nav.nav-tabs.nav-box.nav-box-fix.mt-3
  li.nav-item
    = link_to t(:tweets, scope: 'views.users.shared'), profile_path,
      class: class_names('nav-link', active: current_page?(profile_path))

  li.nav-item
    = link_to t(:mentions, scope: 'views.users.shared'), profile_mentions_path,
      class: class_names('nav-link', active: current_page?(profile_mentions_path))

app/views/profiles/followers.html.slim
= content_for :title
  title
    = t(:followers, scope: "views.title.profiles",
      username: user.username, profilename: user.profilename)

= content_for :header
  = render partial: "profiles/pheader", locals: { user: user }

= content_for :left_panel
  = render partial: "profiles/pleft", locals: { user: user }

div.mt-3
  div.row
    - user_followers.each do |follower|
      div.col-6.mb-3
        =  follower.profile_summary_box(1, include_extras: true)

app/views/profiles/following.html.slim
= content_for :title
  title
    = t(:following, scope: "views.title.profiles",
      username: user.username, profilename: user.profilename)

= content_for :header
  = render partial: "profiles/pheader", locals: { user: user }

= content_for :left_panel
  = render partial: "profiles/pleft", locals: { user: user }

div.mt-3
  div.row
    - user_following.each do |following|
      div.col-6.mb-3
        = following.profile_summary_box(2)

app/views/profiles/likes.html.slim
= content_for :title
  title
    = t(:likes, scope: "views.title.profiles",
      username: user.username, profilename: user.profilename)

= content_for :header
  = render partial: "profiles/pheader", locals: { user: user }

= content_for :left_panel
  = render partial: "profiles/pleft", locals: { user: user }

= content_for :right_panel
  div.box-fix.mt-3
    = render_follow_suggestions_box

    = render_footer_box


div.box-fix.mt-3
  div.box
    = render partial: 'components/feed', collection: feeds, as: :feed

app/views/profiles/mentions.html.slim
= content_for :title
  title
    = t(:show, scope: "views.title.profiles",
      username: user.username, profilename: user.profilename)

= content_for :header
  = render partial: "profiles/pheader", locals: { user: user }

= content_for :left_panel
  = render partial: "profiles/pleft", locals: { user: user }

= content_for :right_panel
  div.box-fix.mt-3
    = render_follow_suggestions_box

    = render_footer_box

/ Main content
= render 'profiles/tnav'

div.box-fix
  div.box#feedStream
    = render partial: "components/feed", collection: feeds, as: :feed

app/views/profiles/show.html.slim
= content_for :title
  title
    = t(:show, scope: "views.title.profiles",
      username: user.username, profilename: user.profilename)

= content_for :header
  = render partial: "profiles/pheader", locals: { user: user }

= content_for :left_panel
  = render partial: "profiles/pleft", locals: { user: user }

= content_for :right_panel
  div.box-fix.mt-3
    = render_follow_suggestions_box

    = render_footer_box

/ Main content
= render 'profiles/tnav'

div.box-fix
  div.box#feedStream
    = render partial: "components/feed", collection: feeds, as: :feed