config/routes.rb
Rails.application.routes.draw do
  get 'api/index'

  get 'home/index'

  get '/:locale', locale: /en|ja|vi/, to: 'home#index'
  root to: 'home#index'

  scope '(:locale)', locale: /en|ja|vi/ do
    devise_for :users, skip: [:registrations, :unlocks], controllers: {
      # registrations: 'users/registrations',
      # unlocks: 'users/unlocks',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
    }

    as :user do
      get    'sign_up', to: 'users/registrations#new',
        as: :new_user_registration
      get    'users/cancel',  to: 'users/registrations#cancel',
        as: :cancel_user_registration
      post   'users',         to: 'users/registrations#create',
        as: :user_registration
      delete 'users',         to: 'users/registrations#destroy'

      get    'settings/password', to: 'users/settings/passwords#edit',
        as: :edit_user_settings_password
      put    'settings/password', to: 'users/settings/passwords#update',
        as: :user_settings_password
      patch  'settings/password', to: 'users/settings/passwords#update'

      get    'settings/account', to: 'users/settings/accounts#edit',
        as: :edit_user_settings_account
      put    'settings/account', to: 'users/settings/accounts#update',
        as: :user_settings_account
      patch  'settings/account', to: 'users/settings/accounts#update'
    end

    namespace :users do
      post '/:user_id', to: 'followings#create', as: :followings
      delete '/:user_id', to: 'followings#destroy'
    end

    scope module: :profiles do
      get ':user_id', action: :show, as: :profile
      get ':user_id/mentions', action: :mentions, as: :profile_mentions
      get ':user_id/followers', action: :followers, as: :profile_followers
      get ':user_id/following', action: :following, as: :profile_following
      get ':user_id/likes', action: :likes, as: :profile_likes
    end

    scope module: :feeds do
      resources :tweets, only: [:show, :update, :create, :destroy] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    scope module: :replies do
      resources :replies, only: [] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    resources :tweets, only: [] do
      resources :replies, shallow: true, controller: "tweets/replies" do
        resources :replies, only: [:create, :new, :index], controller: "tweets/replies"
      end

      resources :hashtags, shallow: true, only: :show, controller: "tweets/hashtags"
    end

    namespace :search do
      get 'users'
      get 'hashtags'
      get 'tweets'
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  decorates_assigned :users, :hashtags, :tweets

  def users
    results = ::User.search(
      params[:q],
      search_params.merge({ fields: [:username, :profilename] })
    )
    @users = UserDecorator.decorate_collection(results)
  end

  # def hashtags
  #   @hashtags = ::Tweet::Hashtag.search(
  #     params[:q],
  #     search_params.merge({ fields: [:name] })
  #   )
  # end

  def tweets
    results = ::Feed::Tweet.search(
      params[:q],
      search_params.merge({ fields: [:content], match: :word })
    )
    @tweets = Feed::TweetDecorator.decorate_collection(results)
  end

private

  def search_params
    {
      page: params[:page] || 1,
      per_page: params[:per_page] || 20,
      match: :word_middle
    }
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_header.html.slim
- content_for :title
  title
    | #{keyword} - Twitter

- content_for :header
  div.query-header
    div.query-title
      .container
        h3 = keyword

    div.query-nav
      .container
        = render 'search/nav'

app/views/search/_nav.html.slim
ul.nav.nav-tabs
  li.nav-item
    = link_to search_users_path(request.query_parameters),
      class: class_names('nav-link', active: current_page?(search_users_path)) do
      = t(:users, scope: 'views.search.shared.nav')

  / li.nav-item
  /   = link_to search_hashtags_path(request.query_parameters),
  /     class: class_names('nav-link', active: current_page?(search_hashtags_path)) do
  /     = t(:hashtags, scope: 'views.search.shared.nav')

  li.nav-item
    = link_to search_tweets_path(request.query_parameters),
      class: class_names('nav-link', active: current_page?(search_tweets_path)) do
      = t(:tweets, scope: 'views.search.shared.nav')

app/views/search/hashtags.html.slim
= render partial: 'search/header', locals: { keyword: params[:q] }

- content_for :left_panel
  div.box-fix
    = render_follow_suggestions_box
    = render_footer_box

- content_for :right_panel
  div.keep

/ div.box-fix#feedStream
/   div.box
/     = render partial: "components/tweet_box", collection: tweets, as: :tweet

app/views/search/tweets.html.slim
= render partial: 'search/header', locals: { keyword: params[:q] }

- content_for :left_panel
  div.box-fix
    = render_follow_suggestions_box
    = render_footer_box

- content_for :right_panel
  div.keep

div.box-fix#feedStream
  div.box
    = render partial: "components/tweet_box", collection: tweets, as: :tweet

app/views/search/users.html.slim
= render partial: 'search/header', locals: { keyword: params[:q] }

- content_for :left_panel
  div.box-fix
    = render_follow_suggestions_box
    = render_footer_box

div.row
  - users.each do |user|
    div.col-6 = user.profile_summary_box(2)