config/routes.rb
Rails.application.routes.draw do
  get 'api/index'

  get 'home/index'

  get '/:locale', locale: /en|ja|vi/, to: 'home#index'
  root to: 'home#index'

  scope '(:locale)', locale: /en|ja|vi/ do
    devise_for :users, skip: [:registrations, :unlocks], controllers: {
      # registrations: 'users/registrations',
      # unlocks: 'users/unlocks',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
    }

    as :user do
      get    'sign_up', to: 'users/registrations#new',
        as: :new_user_registration
      get    'users/cancel',  to: 'users/registrations#cancel',
        as: :cancel_user_registration
      post   'users',         to: 'users/registrations#create',
        as: :user_registration
      delete 'users',         to: 'users/registrations#destroy'

      get    'settings/password', to: 'users/settings/passwords#edit',
        as: :edit_user_settings_password
      put    'settings/password', to: 'users/settings/passwords#update',
        as: :user_settings_password
      patch  'settings/password', to: 'users/settings/passwords#update'

      get    'settings/account', to: 'users/settings/accounts#edit',
        as: :edit_user_settings_account
      put    'settings/account', to: 'users/settings/accounts#update',
        as: :user_settings_account
      patch  'settings/account', to: 'users/settings/accounts#update'
    end

    namespace :users do
      post '/:user_id', to: 'followings#create', as: :followings
      delete '/:user_id', to: 'followings#destroy'
    end

    scope module: :profiles do
      get ':user_id', action: :show, as: :profile
      get ':user_id/mentions', action: :mentions, as: :profile_mentions
      get ':user_id/followers', action: :followers, as: :profile_followers
      get ':user_id/following', action: :following, as: :profile_following
      get ':user_id/likes', action: :likes, as: :profile_likes
    end

    scope module: :feeds do
      resources :tweets, only: [:show, :update, :create, :destroy] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    scope module: :replies do
      resources :replies, only: [] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    resources :tweets, only: [] do
      resources :replies, shallow: true, controller: "tweets/replies" do
        resources :replies, only: [:create, :new, :index], controller: "tweets/replies"
      end

      resources :hashtags, shallow: true, only: :show, controller: "tweets/hashtags"
    end

    namespace :search do
      get 'users'
      get 'hashtags'
      get 'tweets'
    end
  end
end

app/controllers/users/settings/accounts_controller.rb
class Users::Settings::AccountsController < Devise::RegistrationsController
  layout 'setting'

  before_action :configure_account_update_params, only: [:update]

  # Return view to edit profile
  def edit
    super
  end

  # Save profile changes
  def update
    super
  end

  # Deactive account
  def destroy
    super
  end

protected

  # User can update information without providing current password
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # Attributes user can change without password
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :username, :profilename, :avatar, :cover, :birthday, :birthday_visibility,
      :country, :language
    ])
  end

  # Redirect to change profile page after saving changes
  def after_update_path_for(resource)
    edit_user_settings_account_path
  end
end

app/controllers/users/settings/passwords_controller.rb
class Users::Settings::PasswordsController < Devise::RegistrationsController
  layout 'setting'

  # Returns view to change password
  def edit
    super
  end

  # Save new password
  def update
    super
  end

protected

  # Redirect user to change password page after saving new password
  def after_update_path_for(resource)
    edit_user_settings_password_path
  end
end

app/helpers/users/settings/accounts_helper.rb
module Users::Settings::AccountsHelper
  def settings_account_path?
    current_page?(controller: "users/settings/accounts", action: :edit) ||
    current_page?(controller: "users/settings/accounts", action: :update)
  end
end

app/helpers/users/settings/passwords_helper.rb
module Users::Settings::PasswordsHelper
  def settings_password_path?
    current_page?(controller: "users/settings/passwords", action: :edit) ||
    current_page?(controller: "users/settings/passwords", action: :update)
  end
end

app/views/users/settings/accounts/edit.html.slim
= content_for :title do
  title = t(:header, scope: 'views.users.settings.account.edit')

= content_for :left_panel do
  = render 'users/settings/shared/left_panel'

= flash_info

= form_for(resource, as: resource_name, url: user_settings_account_path, html: { method: :put }) do |f|
  div.box-fix
    div.box
      div.box-item
        h4 = t(:header, scope: 'views.users.settings.account.edit')

      div.box-item
        div class="box-item-header"
          h5 = t(:profile, scope: 'views.users.settings.account.edit')

        div class="form-group input-field"
          = f.text_field :username, autofocus: true, class: "form-control"
          = f.label :username
          small class="form-text text-muted"
            | https://twitter.com/[your_username]

        div class="form-group input-field"
          = f.text_field :profilename, class: "form-control"
          = f.label :profilename

          = show_errors(resource, :password_confirmation)
        div class="form-group input-field"
          = f.email_field :email, autocomplete: "email",
            class: "form-control"
          = f.label :email

          = show_errors(resource, :email)

        div class="custom-file"
          = f.file_field :avatar, class: "custom-file-input"
          = f.label :avatar,  class: "custom-file-label"

          = show_errors(resource, :avatar)

        div class="custom-file"
          = f.file_field :cover, class: "custom-file-input"
          = f.label :cover,  class: "custom-file-label"

          = show_errors(resource, :cover)


      div.box-item
        div class="box-item-header"
          h5 = t(:addition, scope: 'views.users.settings.account.edit')

        div class="form-group input-field"
          = f.text_field :birthday, class: "form-control"
          = f.label :birthday

          = show_errors(resource, :birthday)

        div class="form-group input-field"
          = f.text_field :birthday_visibility, class: "form-control"
          = f.label :birthday_visibility

          = show_errors(resource, :birthday_visibility)

      div.box-item
        div class="box-item-header"
          h5 = t(:content, scope: 'views.users.settings.account.edit')

        div class="form-group input-field"
          = f.text_field :country, class: "form-control"
          = f.label :country

          = show_errors(resource, :country)

        div class="form-group input-field"
          = f.text_field :language, class: "form-control"
          = f.label :language

          = show_errors(resource, :language)

        div class="actions text-center pt-2"
          = f.submit t(:update, scope: 'defaults'),
            class: 'btn btn-primary btn-edge'

      div.box-item.text-center.py-4
        = link_to t(:deactive, scope: 'views.users.settings.account.edit'), registration_path(resource_name),
          data: { confirm: "Are you sure?" }, method: :delete