config/routes.rb
Rails.application.routes.draw do
  get 'api/index'

  get 'home/index'

  get '/:locale', locale: /en|ja|vi/, to: 'home#index'
  root to: 'home#index'

  scope '(:locale)', locale: /en|ja|vi/ do
    devise_for :users, skip: [:registrations, :unlocks], controllers: {
      # registrations: 'users/registrations',
      # unlocks: 'users/unlocks',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
    }

    as :user do
      get    'sign_up', to: 'users/registrations#new',
        as: :new_user_registration
      get    'users/cancel',  to: 'users/registrations#cancel',
        as: :cancel_user_registration
      post   'users',         to: 'users/registrations#create',
        as: :user_registration
      delete 'users',         to: 'users/registrations#destroy'

      get    'settings/password', to: 'users/settings/passwords#edit',
        as: :edit_user_settings_password
      put    'settings/password', to: 'users/settings/passwords#update',
        as: :user_settings_password
      patch  'settings/password', to: 'users/settings/passwords#update'

      get    'settings/account', to: 'users/settings/accounts#edit',
        as: :edit_user_settings_account
      put    'settings/account', to: 'users/settings/accounts#update',
        as: :user_settings_account
      patch  'settings/account', to: 'users/settings/accounts#update'
    end

    namespace :users do
      post '/:user_id', to: 'followings#create', as: :followings
      delete '/:user_id', to: 'followings#destroy'
    end

    scope module: :profiles do
      get ':user_id', action: :show, as: :profile
      get ':user_id/mentions', action: :mentions, as: :profile_mentions
      get ':user_id/followers', action: :followers, as: :profile_followers
      get ':user_id/following', action: :following, as: :profile_following
      get ':user_id/likes', action: :likes, as: :profile_likes
    end

    scope module: :feeds do
      resources :tweets, only: [:show, :update, :create, :destroy] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    scope module: :replies do
      resources :replies, only: [] do
        member do
          get    'like', to: 'likes#index',   as: :like
          post   'like', to: 'likes#create'
          delete 'like', to: 'likes#destroy'

          get    'retweet', to: 'retweets#index',   as: :retweet
          post   'retweet', to: 'retweets#create'
          delete 'retweet', to: 'retweets#destroy'
        end
      end
    end

    resources :tweets, only: [] do
      resources :replies, shallow: true, controller: "tweets/replies" do
        resources :replies, only: [:create, :new, :index], controller: "tweets/replies"
      end

      resources :hashtags, shallow: true, only: :show, controller: "tweets/hashtags"
    end

    namespace :search do
      get 'users'
      get 'hashtags'
      get 'tweets'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :determine_layout

  decorates_assigned :feeds

  def index
    if user_signed_in?
      @feeds = FeedDecorator.decorate_collection(
        Feed.for(current_user).includes(tweet: :user, retweet: [:tweet, :user], like: [:tweet, :user])
      )
    end
  end

private

  def determine_layout
    user_signed_in? ? "application" : "full_page"
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def root_path?
    current_page?(root_path)
  end
end

app/views/home/_guest.html.slim
= content_for :title do
  title = t(:title, scope: "views.home.guest")

div.static-home-page
  div.static-home-page-cell
    div.communication-block
      div.communication-item
        i class="fas fa-search fa-fw"
        span = t(:first, scope: "views.home.guest")

      div.communication-item
        i class="fas fa-users fa-fw"
        span = t(:second, scope: "views.home.guest")

      div.communication-item
        i class="far fa-comment fa-fw"
        span = t(:third, scope: "views.home.guest")

  div.static-home-page-cell
    div.join-us-block
      div.join-us-header
        i class="fab fa-twitter"

      div.join-us-messages.pt-3
        p.message = t(:message, scope: 'views.home.guest')
        p.join-us = t(:join_us, scope: 'views.home.guest')

      div.join-us-links.py-2
        div
          = t(:guest, scope: 'views.home.guest')
          span &nbsp;
          = link_to new_registration_path(:user) do
            = t(:sign_up_full, scope: 'views.users.shared')
        div
          = t(:user, scope: 'views.home.guest')
          span &nbsp;
          = link_to new_session_path(:user) do
            = t(:sign_in_full, scope: 'views.users.shared')

app/views/home/_user.html.slim
= content_for :title do
  title = t(:app_name, scope: "defaults")

= content_for :left_panel do
  = current_user.profile_summary_box(1, include_extras: true)

= content_for :right_panel do
  div.box-fix
    = render_follow_suggestions_box

    = render_footer_box

div.box-fix
  div.box-mb-0
    div.new-tweet-composer
      = render partial: "components/tweet_composer"
  div.box#feedStream
    = render partial: "components/feed", collection: feeds, as: :feed

app/views/home/index.html.slim
- if user_signed_in?
  = render "home/user"
- else
  = render "home/guest"